### ISSUE TITLE
Empty Changeset function throws error

### ISSUE THREAD

**Issue by aswinmohanme** [testdouble/ecto_resource#5]
I have a `Books` Context with the `Book` resource. On the `BookController` I have this code.

  ```
def new(conn, _params) do
    changeset = Books.change_book(%{})
    render(conn, "new.html", changeset: changeset)
  end
```

But calling this throws 
```
iex(7)> IndiePaper.Books.change_book(%{})
** (FunctionClauseError) no function clause matching in Ecto.Changeset.cast/4

    The following arguments were given to Ecto.Changeset.cast/4:

        # 1
        %{}

        # 2
        %{}

        # 3
        [:title, :description]

        # 4
        []

    Attempted function clauses (showing 5 out of 5):

        def cast(_data, %{__struct__: _} = params, _permitted, _opts)
        def cast({data, types}, params, permitted, opts) when is_map(data)
        def cast(%Ecto.Changeset{types: nil}, _params, _permitted, _opts)
        def cast(%Ecto.Changeset{changes: changes, data: data, types: types, empty_values: empty_values} = changeset, params, permitted, opts)
        def cast(%{__struct__: module} = data, params, permitted, opts)

    (ecto 3.5.6) lib/ecto/changeset.ex:466: Ecto.Changeset.cast/4
    (indie_paper 0.1.0) lib/indie_paper/books/book.ex:17: IndiePaper.Books.Book.changeset/2

```

Any idea on how to fix this ?

Here is my Books Context for reference
```
defmodule IndiePaper.Books do
  alias IndiePaper.{Repo}

  use EctoResource

  using_repo(Repo) do
    resource(IndiePaper.Books.Book)
  end
end
```

Here is the `Book` Schema
```
defmodule IndiePaper.Books.Book do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "books" do
    field :title, :string
    field :description, :string

    timestamps()
  end

  @doc false
  def changeset(book, attrs \\ %{}) do
    book
    |> cast(attrs, [:title, :description])
    |> validate_required([:title, :description])
    |> unique_constraint(:title)
  end
end

```

**Comment by daytonn** [comment]
This is addressed in the latest release `1.3.1` which adds a `changeset` function that provides the ability to generate an empty changeset for the given schema. In your example you can replace `Books.change_book(%{})` with `Books.changeset()`.
